language: java
jdk:
  - oraclejdk8

install: /bin/true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
    - /^ready\/.*$/

before_script:
  - sh -ex ci/before.sh

script:
  - ./gradlew test

after_script:
  - sh -ex ci/after.sh